$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-deployment-mahi2
endpoint_name: mlflow-endpoint-mahi
model: azureml:my-model2@latest
instance_type: Standard_DS2_v2
instance_count: 1
